# Generated by Django 2.2.6 on 2019-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='employees',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='projects',
            field=models.ManyToManyField(to='employee.Projects'),
        ),
    ]
