# Generated by Django 2.2.6 on 2019-10-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191020_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
